<?php

namespace AppBundle\Repository;

/**
 * ManualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManualRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return string
     */
    public function prueba()
    {   //TODO-IMPORTANT Begin a method for dev
        return 'ok';
    }
}
