# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    utilities:
        class: AppBundle\Util\Utility
        arguments: 
              entityManager: "@doctrine.orm.entity_manager"
              session: "@session"

    manual:
         class: AppBundle\Infrastructure\ManualAction
         arguments:
               entityManager: "@doctrine.orm.entity_manager"
               session: "@session"